### ISSUE TITLE
Create benchmark to find fastest t_method

### ISSUE THREAD

**Issue by garrettj403** [garrettj403/CZT#9]
``czt`` has several different options for ``t_method``. These methods should be compared via a benchmark to find the fastest option, which should then become the default.

**Comment by LarsHuebner-LHNW** [comment]
There you go. method="mm" raises a MemoryError if array-size is too large, so don't get confused by the drop in computation time there. I did not test the f_method="fast" because of all the warnings about not working correctly.
![czt](https://user-images.githubusercontent.com/57982411/109338099-19d02200-7866-11eb-90c7-0da4c174cdd5.png)

**Comment by garrettj403** [comment]
Thanks @LarsHuebner-LHNW 

I didn't see your comment in time, so I created my own simple benchmark (see 1066414). I also found that ``t_method='scipy'`` is the fastest option.

I changed the default ``t_method`` to ``'scipy'`` in 5009cdb.
